import StyledComponentsRegistry from "@/lib/registry";

export const metadata = {
  title: "XOC Tattoo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="de">
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
